### ISSUE TITLE
1.20 : Application ID invalid.

### ISSUE THREAD

**Issue by Blackir62** [rishiv3/ebayAddItem#2]
Hello,

I followed the indications, ask for a key API production ebay, but impossible to run php script.
I always have the issue 1.20 : Application ID invalid., but the key is ok.
Do you have an idea ? thanks.

![capture du 2017-07-06 17-24-49](https://user-images.githubusercontent.com/26694751/27919022-e2bfe91c-6270-11e7-8dc9-44ba166f8f01.png)
![capture du 2017-07-06 17-25-02](https://user-images.githubusercontent.com/26694751/27919023-e2c0366a-6270-11e7-87dc-3e7260169c79.png)
![capture du 2017-07-06 17-28-18](https://user-images.githubusercontent.com/26694751/27919024-e2c234e2-6270-11e7-9995-2eeed7980838.png)

**Comment by snipeo** [comment]
the same here

**Comment by ChizhovMichael** [comment]
In index.php $ endpoint = 'http://open.api.ebay.com/shopping';
It works

**Comment by rishiv3** [comment]
@ChizhovMichael good job man 👍 
@snipeo  That link in the index file is for sandbox but you can use 'http://open.api.ebay.com/shopping' as mentioned by ChizhovMichael.

**Comment by pawanguleria** [comment]
Hi The problem is same. when we click on the category to get it's sub cat it reurn this error.
1.20 : Application ID invalid.
Application ID invalid.
if anyone have idea to how to fix this please help.

thanks
![Screenshot from 2020-03-05 12-29-51](https://user-images.githubusercontent.com/32273291/75956105-30ef6480-5edd-11ea-94d5-909e860200bf.png)
